export const products = [
    {
        id: "bananas",
        vendor: "Green Valley Farms",
        name: "Fresh Organic Bananas",
        category: "Fruits & Vegetables",
        unit: "1 kg",
        price: 2.99,
        oldPrice: 3.99,
        rating: 4.8,
        reviews: 124,
        image: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=500&q=85",
        badge: "25% OFF",
    },
    {
        id: "avocados",
        vendor: "Organic Oasis",
        name: "Premium Ripe Avocados",
        category: "Fruits & Vegetables",
        unit: "500 g",
        price: 4.5,
        oldPrice: null,
        rating: 4.9,
        reviews: 85,
        image: "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=500&q=85",
    },
    {
        id: "spinach",
        vendor: "Local Harvest",
        name: "Fresh Baby Spinach Leaves",
        category: "Fruits & Vegetables",
        unit: "250 g",
        price: 1.99,
        oldPrice: null,
        rating: 4.7,
        reviews: 210,
        image: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=500&q=85",
    },
    {
        id: "apples",
        vendor: "Sunshine Orchards",
        name: "Crisp Red Apples (Fuji)",
        category: "Fruits & Vegetables",
        unit: "1 kg",
        price: 5.99,
        oldPrice: null,
        rating: 4.6,
        reviews: 342,
        image: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=500&q=85",
    },
    {
        id: "carrots",
        vendor: "Earth's Best",
        name: "Fresh Organic Carrots",
        category: "Fruits & Vegetables",
        unit: "1 kg",
        price: 1.49,
        oldPrice: null,
        rating: 4.8,
        reviews: 95,
        image: "https://images.unsplash.com/photo-1445282768818-728615cc910a?auto=format&fit=crop&w=500&q=85",
    },
    {
        id: "broccoli",
        vendor: "Green Valley Farms",
        name: "Fresh Broccoli Crown",
        category: "Fruits & Vegetables",
        unit: "1 pc (approx 400g)",
        price: 2.49,
        oldPrice: 3,
        rating: 4.5,
        reviews: 118,
        image: "https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?auto=format&fit=crop&w=500&q=85",
        badge: "15% OFF",
    },
    {
        id: "sweet-potatoes",
        vendor: "Root Farms",
        name: "Organic Sweet Potatoes",
        category: "Fruits & Vegetables",
        unit: "1 kg",
        price: 3.29,
        oldPrice: null,
        rating: 4.9,
        reviews: 76,
        image: "https://images.unsplash.com/photo-1596097635121-14b63b7a0c19?auto=format&fit=crop&w=500&q=85",
    },
    {
        id: "strawberries",
        vendor: "Berry Fresh",
        name: "Fresh Juicy Strawberries",
        category: "Fruits & Vegetables",
        unit: "400 g",
        price: 4.99,
        oldPrice: 6.5,
        rating: 4.7,
        reviews: 412,
        image: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=500&q=85",
        badge: "20% OFF",
    },
    {
        id: "mangoes",
        vendor: "Tropical Farms",
        name: "Sweet Alphonso Mangoes",
        category: "Fruits & Vegetables",
        unit: "1 kg",
        price: 6.49,
        oldPrice: null,
        rating: 4.8,
        reviews: 96,
        image: "https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&w=500&q=85",
    },
    {
        id: "milk",
        vendor: "Valley Dairy",
        name: "Farm Fresh Whole Milk",
        category: "Dairy & Breakfast",
        unit: "1 Liter",
        price: 2.5,
        oldPrice: null,
        rating: 4.7,
        reviews: 184,
        image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=500&q=85",
    },
    {
        id: "paneer-tikka",
        vendor: "Local Harvest",
        name: "Ready-to-Cook Paneer Tikka",
        category: "Vegetarian",
        unit: "400 g",
        price: 5.49,
        oldPrice: 6.25,
        rating: 4.6,
        reviews: 72,
        image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=500&q=85",
        badge: "12% OFF",
    },
    {
        id: "vegetable-samosa",
        vendor: "Earth's Best",
        name: "Crispy Vegetable Samosas",
        category: "Vegetarian",
        unit: "Pack of 8",
        price: 3.99,
        oldPrice: null,
        rating: 4.7,
        reviews: 58,
        image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=500&q=85",
    },
    {
        id: "vegetable-pasta",
        vendor: "Green Valley Farms",
        name: "Garden Vegetable Pasta",
        category: "Vegetarian",
        unit: "500 g",
        price: 4.25,
        oldPrice: null,
        rating: 4.5,
        reviews: 44,
        image: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=500&q=85",
    },
    {
        id: "chicken-breast",
        vendor: "Fresh Meat Co.",
        name: "Fresh Boneless Chicken Breast",
        category: "Non-Vegetarian",
        unit: "500 g",
        price: 7.99,
        oldPrice: null,
        rating: 4.8,
        reviews: 131,
        image: "https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=500&q=85",
    },
    {
        id: "chicken-nuglet",
        vendor: "Fresh Meat Co.",
        name: "Fresh Boneless Chicken Nuglets",
        category: "Non-Vegetarian",
        unit: "500 g",
        price: 7.99,
        oldPrice: null,
        rating: 4.8,
        reviews: 131,
        image: "https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=500&q=85",
    },
    {
        id: "salmon-fillets",
        vendor: "Ocean Catch",
        name: "Fresh Salmon Fillets",
        category: "Non-Vegetarian",
        unit: "400 g",
        price: 12.99,
        oldPrice: 14.5,
        rating: 4.9,
        reviews: 86,
        image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=500&q=85",
        badge: "10% OFF",
    },
    {
        id: "mutton-curry-cut",
        vendor: "Fresh Meat Co.",
        name: "Tender Mutton Curry Cut",
        category: "Non-Vegetarian",
        unit: "500 g",
        price: 10.49,
        oldPrice: null,
        rating: 4.6,
        reviews: 63,
        image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=500&q=85",
    },
    {
        id: "mutton-nuglet",
        vendor: "Fresh Meat Co.",
        name: "Tender Mutton Nuglets",
        category: "Non-Vegetarian",
        unit: "500 g",
        price: 10.49,
        oldPrice: null,
        rating: 4.6,
        reviews: 63,
        image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=500&q=85",
    },
];

export const featuredProducts = [
    {
        id: "tomatoes",
        vendor: "Sunrise Farms",
        name: "Fresh Organic Red Tomatoes",
        unit: "1 kg",
        price: 4.25,
        oldPrice: 5.0,
        stock: 10,
        image: "https://images.unsplash.com/photo-1546094096-0df4bcaaa337?auto=format&fit=crop&w=400&q=80",
        badges: [
            { label: "15% OFF", color: "bg-red-500" },
            { label: "Organic", color: "bg-green-600" },
        ],
    },
    {
        id: "featured-milk",
        vendor: "Valley Dairy",
        name: "Farm Fresh Whole Milk",
        unit: "1 Liter",
        price: 2.5,
        oldPrice: null,
        stock: 0,
        image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=400&q=80",
        badges: [{ label: "Farm Fresh", color: "bg-green-600" }],
    },
    {
        id: "featured-avocados",
        vendor: "Green Valley Organics",
        name: "Premium Hass Avocados",
        unit: "Pack of 3",
        price: 6.99,
        oldPrice: null,
        stock: 5,
        image: "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=400&q=80",
        badges: [],
    },
    {
        id: "sourdough",
        vendor: "Artisan Bakers",
        name: "Classic Sourdough Loaf",
        unit: "400 g",
        price: 4.5,
        oldPrice: 5.0,
        stock: 0,
        image: "https://images.unsplash.com/photo-1585478259715-4d3c5ee36e2c?auto=format&fit=crop&w=400&q=80",
        badges: [{ label: "10% OFF", color: "bg-red-500" }],
    },
];

export const getSearchSuggestions = (value) => {
    const query = value.trim().toLowerCase();
    if (!query) return [];

    return products
        .filter((product) =>
            `${product.name} ${product.category} ${product.vendor}`
                .toLowerCase()
                .includes(query),
        )
        .slice(0, 5);
};
